apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":"2023-01-18T06:32:42Z","generation":1,"labels":{"app.kubernetes.io/instance":"aws-vpc-cni","app.kubernetes.io/name":"aws-node","app.kubernetes.io/version":"v1.11.4","k8s-app":"aws-node"},"name":"eniconfigs.crd.k8s.amazonaws.com","resourceVersion":"174035826","uid":"0049e45c-5166-4fc9-ae87-aa40f6bb5fbb"},"spec":{"conversion":{"strategy":"None"},"group":"crd.k8s.amazonaws.com","names":{"kind":"ENIConfig","listKind":"ENIConfigList","plural":"eniconfigs","singular":"eniconfig"},"scope":"Cluster","versions":[{"name":"v1alpha1","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":true}]},"status":{"acceptedNames":{"kind":"ENIConfig","listKind":"ENIConfigList","plural":"eniconfigs","singular":"eniconfig"},"conditions":[{"lastTransitionTime":"2023-01-18T06:32:42Z","message":"no conflicts found","reason":"NoConflicts","status":"True","type":"NamesAccepted"},{"lastTransitionTime":"2023-01-18T06:32:42Z","message":"the initial names have been accepted","reason":"InitialNamesAccepted","status":"True","type":"Established"}],"storedVersions":["v1alpha1"]}}
  creationTimestamp: "2023-01-18T06:32:42Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: aws-vpc-cni
    app.kubernetes.io/name: aws-node
    app.kubernetes.io/version: v1.11.4
    k8s-app: aws-node
  name: eniconfigs.crd.k8s.amazonaws.com
  resourceVersion: "174037337"
  uid: 0049e45c-5166-4fc9-ae87-aa40f6bb5fbb
spec:
  conversion:
    strategy: None
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ENIConfig is the Schema for the eniconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ENIConfigSpec defines the desired state of ENIConfig
            properties:
              securityGroups:
                items:
                  type: string
                type: array
              subnet:
                type: string
            required:
            - subnet
            type: object
          status:
            description: ENIConfigStatus defines the observed state of ENIConfig
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
status:
  acceptedNames:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  conditions:
  - lastTransitionTime: "2023-01-18T06:32:42Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-01-18T06:32:42Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
